#cloud-config

hostname: kmaster
users:
  - name: giom
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - 

bootcmd:
    - echo 127.0.0.1 kmaster >> /etc/hosts

runcmd:
  - [kubeadm, init, --apiserver-advertise-address=192.168.120.230, --ignore-preflight-errors=all]
  - [kubectl, --kubeconfig=/etc/kubernetes/admin.conf, create, -f, https://docs.projectcalico.org/v3.14/manifests/calico.yaml]
  - [kubeadm, token, create, --print-join-command]


  
